/*
 * Winime API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: kik0908369@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShortAnimeInfo struct {

	Id int64 `json:"id"`

	Name string `json:"name"`

	PathToImage string `json:"pathToImage"`

	Rating float32 `json:"rating"`
}
