/*
 * Winime API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: kik0908369@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FullAnimeInfo struct {

	Id int64 `json:"id"`

	Name string `json:"name"`

	OriginName string `json:"originName"`

	Genres *[]string `json:"genres"`
	// *May be empty*!
	Description string `json:"description"`
	// Paths to Poster
	Poster string `json:"poster"`
	// Paths to images
	Images []string `json:"images,omitempty"`
}
