/*
 * Winime API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: kik0908369@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShortAnimeAnswer struct {
	// Actual quantity
	Count int32 `json:"count"`
	// Array with short title info
	Titles []ShortAnimeInfo `json:"titles"`
}
