openapi: 3.0.3
info:
  title: Winime API
  contact:
    email: kik0908369@gmail.com
  version: 1.0.0
servers:
- url: http://localhost/api
  description: Your local server
tags:
- name: anime
  description: Interaction of an ordinary user with anime
- name: user
  description: User
- name: admin
  description: Admin panel
paths:
  /anime/top/{count}:
    get:
      tags:
      - anime
      summary: Get the first 'count' entries from the top by rating
      parameters:
      - name: count
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maximum: 100
          minimum: 1
          type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortAnimeAnswer'
        "500":
          description: Internal server error
  /anime:
    get:
      tags:
      - anime
      description: "Get 20 or less(maybe if it is the last page) anime in sorted order\
        \ by rating, date added, release date. You can specify the desired genres.\
        \ You must specify the **page**."
      parameters:
      - name: page
        in: query
        description: Num of page
        required: true
        style: form
        explode: true
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      - name: sort_by
        in: query
        description: "Sort by rating(r), date added(ad) or release date(rd)."
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - r
          - ad
          - rd
          default: ad
      - name: genres
        in: query
        description: List of genres
        required: true
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/Genres'
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortAnimeAnswer'
        "500":
          description: Internal server error
  /anime/{id}:
    get:
      tags:
      - anime
      summary: Get anime by ID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maximum: 9999999
          minimum: 1
          type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullAnimeInfo'
components:
  schemas:
    Genres:
      minItems: 1
      type: array
      example:
      - Action
      - Detective
      items:
        type: string
      default:
      - all
      x-schema-name: Genres
    Id:
      type: integer
      description: Id of title
      format: int64
      example: 1
    Rating:
      type: number
      description: Rating of title
      format: float
      example: 5.6
    ShortAnimeInfo:
      required:
      - id
      - name
      - pathToImage
      - rating
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          type: string
          example: Boku no Piko
        pathToImage:
          type: string
          example: /img/0000001/img.png
        rating:
          $ref: '#/components/schemas/Rating'
      example:
        pathToImage: /img/0000001/img.png
        name: Boku no Piko
        rating: 5.6
        id: 1
    ShortAnimeAnswer:
      required:
      - count
      - titles
      type: object
      properties:
        count:
          type: integer
          description: Actual quantity
          default: 1
        titles:
          type: array
          description: Array with short title info
          items:
            $ref: '#/components/schemas/ShortAnimeInfo'
      example:
        count: 0
        titles:
        - pathToImage: /img/0000001/img.png
          name: Boku no Piko
          rating: 5.6
          id: 1
        - pathToImage: /img/0000001/img.png
          name: Boku no Piko
          rating: 5.6
          id: 1
    FullAnimeInfo:
      required:
      - description
      - genres
      - id
      - name
      - originName
      - poster
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          type: string
          example: Cowboy Bebop
        originName:
          type: string
          example: Cowboy Bebop
        genres:
          $ref: '#/components/schemas/Genres'
        description:
          type: string
          description: '*May be empty*!'
          example: A very cool anime with a ship in the role of a bebop cowboy
        poster:
          type: string
          description: Paths to Poster
          example: /img/0000002/poster.png
        images:
          type: array
          description: Paths to images
          example:
          - /img/0000002/img1.png
          - /img/0000002/img2.png
          items:
            type: string
      example:
        images:
        - /img/0000002/img1.png
        - /img/0000002/img2.png
        genres:
        - Action
        - Detective
        name: Cowboy Bebop
        description: A very cool anime with a ship in the role of a bebop cowboy
        id: 1
        poster: /img/0000002/poster.png
        originName: Cowboy Bebop
